{{- range $path, $cfg := .Values.configMaps | default (dict) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}-config
data:
{{- range $cfg.inline }}
  {{ .name }}: |
{{ .content | indent 4 }}
{{- end }}
---
{{- end }}
