apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
{{- toYaml .Values.annotations | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
{{ include "app.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "app.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "app.fullname" . }}
      containers:
        - name: app
          image: "{{ default "nginx:latest" .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
{{- range .Values.container.ports | default (list (dict "name" "http" "containerPort" 8080 "servicePort" 80 "protocol" "TCP")) }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
{{- end }}
          resources:
{{- toYaml .Values.resources | indent 12 }}
          env:
{{- toYaml .Values.env | indent 12 }}
{{- if .Values.envFromSecrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecrets.name }}
{{- end }}
          livenessProbe:
{{- toYaml .Values.healthchecks.livenessProbe | indent 12 }}
          readinessProbe:
{{- toYaml .Values.healthchecks.readinessProbe | indent 12 }}
{{- if .Values.configMaps }}
          volumeMounts:
{{- range $name, $_ := .Values.configMaps }}
            - name: {{ $name }}
              mountPath: /spring/config/{{ $name }}
{{- end }}
      volumes:
{{- range $name, $_ := .Values.configMaps }}
        - name: {{ $name }}
          configMap:
            name: {{ include "app.fullname" $ }}-{{ $name }}
{{- end }}
{{- end }}
