apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "app.labels" . | indent 4 }}
  ports:
{{- range .Values.container.ports }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
{{- end }}
