{{- $svc := .Values.service | default (dict "type" "ClusterIP") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
spec:
  type: {{ $svc.type }}
  selector:
{{ include "app.labels" . | indent 4 }}
  ports:
{{- $ports := .Values.container.ports | default (list (dict "name" "http" "servicePort" 80 "containerPort" 8080 "protocol" "TCP")) }}
{{- range $ports }}
    - name: {{ .name | default "http" }}
      port: {{ .servicePort | default 80 }}
      targetPort: {{ .containerPort | default 8080 }}
      protocol: {{ .protocol | default "TCP" }}
{{- end }}
