{{- $svc := .Values.service | default (dict "type" "ClusterIP") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ $svc.type }}
  selector:
    {{- include "app.labels" . | nindent 4 }}
  ports:
    {{- if .Values.container.ports }}
    {{- range .Values.container.ports }}
    - name: {{ .name }}
      port: {{ .servicePort | default 80 }}
      targetPort: {{ .containerPort | default 8080 }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- else }}
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    {{- end }}
